# Site settings
title: c-oreills
email: christy@oreills.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Programmer, maths geek, gamer, acrobat, mountaineer, ad hoc MacGyver.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.c-oreills.com" # the base hostname & protocol for your site
github_username:  c-oreills
twitter_username:  c_oreills

# Build settings
highlighter: rouge
markdown: kramdown

exclude:
  - bin

gems:
  - jekyll-sitemap
